working_dir: /tmp/
data_dir: /var/lib/crowdsec/data
config_dir: /etc/crowdsec/config/
pid_dir: /var/run/
log_dir: /var/log/crowdsec/
cscli_dir: /etc/crowdsec/config/cscli
log_mode: file
log_level: info
profiling: false
sqlite_path: /var/lib/crowdsec/data/crowdsec.db
apimode: true
daemon: true
prometheus: true
#for prometheus agent / golang debugging
http_listen: 127.0.0.1:6060
plugin:
  backend: "/etc/crowdsec/plugins/backend"
