name: tests-windows

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'README.md'

jobs:

  build:
    name: Build
    runs-on: windows-2019
    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build
      run: make build && go get -u github.com/jandelgado/gcov2lcov
    - name: All tests
      run: go test -coverprofile=coverage.out -covermode=atomic ./...
    - name: gcov2lcov
      uses: jandelgado/gcov2lcov-action@v1.0.2
      with:
        infile: coverage.out
        outfile: coverage.txt
    - name: Coveralls
      uses: coverallsapp/github-action@master
      continue-on-error: true
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.txt
